FROM node:10.13.0-alpine
RUN apk --no-cache add git python make g++

# Working DIR
WORKDIR /usr/src/app

# Set the env variables
#ARG CONFIG_ID
#ARG GITHUB_TOKEN
#RUN echo "CONFIG_ID=$CONFIG_ID"
#RUN echo "GITHUB_TOKEN=$GITHUB_TOKEN"
#ENV REACT_APP_CONFIG_ID=$CONFIG_ID

# We are npm installing from private repos so we need github token with access
# RUN git config --global url."https://${GITHUB_TOKEN}:@github.com/".insteadOf "https://github.com/"

RUN git clone https://github.com/iotaledger/tangle-utils-website.git .

WORKDIR /usr/src/app/api

# Running required steps to prepare the app prod build
RUN npm install
RUN npm run build

# Remove all the node_modules so the docker image doesn't exceeds max size
RUN apk del git python make g++

EXPOSE 4000:4000

CMD ["node", "./dist/index"]
